---
- name: Install latest Apache on RHEL
  hosts: localhost
  become: yes

  tasks:
    - name: Update package cache
      yum:
        name: '*'
        update_cache: yes

    - name: Install latest Apache
      yum:
        name: httpd
        state: latest

    - name: copy web.html
      copy:
        src: ~/web.html
        dest: /var/www/index.html
