---
- name: python Playbook
  hosts: localhost
  tasks:
    - name: Create Python script
      copy:
        content: |
          #!/usr/bin/env python3
          def fizzbuzz(n):
            for i in range(1, n + 1):
                if i % 15 == 0:
                    print("FizzBuzz")
                elif i % 3 == 0:
                    print("Fizz")
                elif i % 5 == 0:
                    print("Buzz")
                else:
                    print(i)

          fizzbuzz(100)
        dest: /tmp/FizzBuzz.py
        mode: '0755' 

    - name: Execute Python script
      command: python3 /tmp/FizzBuzz.py
